### ISSUE TITLE
Max Result Props undefined 

### ISSUE THREAD

**Issue by auchaphon** [buildingwatsize/thai-address-autocomplete-react#1]
Please Change To
<img width="751" alt="Screen Shot 2565-02-27 at 20 04 28" src="https://user-images.githubusercontent.com/29698585/155883576-197e340f-0c95-4645-9652-dc79372639d9.png">

**Comment by buildingwatsize** [comment]
@auchaphon Thanks for opening an issue, Can you give me more detail about this? maybe some reproduce code or something like that.

**Comment by buildingwatsize** [comment]
Closed after a long time ago, last status: `need more detail`.
